// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import HowToUseTabsController from "./how_to_use_tabs_controller"
application.register("how-to-use-tabs", HowToUseTabsController)

import InputDatetimeController from "./input_datetime_controller"
application.register("input-datetime", InputDatetimeController)

import LinkController from "./link_controller"
application.register("link", LinkController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
